<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>a34c4076-30af-4a06-9ddc-22a080fe2fe7</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\UrlShorter.Application\UrlShorter.Application.csproj" />
        <ProjectReference Include="..\UrlShorter.Infrastructure\UrlShorter.Infrastructure.csproj" />
    </ItemGroup>

</Project>
