services:
  urlshorter-api:
    image: ghcr.io/jadsonserafim/urlshorter-api:latest
    container_name: urlshorter-api
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Host=shared-db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Redis=${REDIS_CONNECTION}
      - Jwt__Secret=${JWT_SECRET}
      - FrontendUrl=${FRONTEND_URL}
      - UrlSafety__GoogleSafeBrowsing__ApiKey=${GOOGLE_SAFE_BROWSING_API_KEY}
      - Whois__ApiKey=${WHOIS_API_KEY}
      - Email__SmtpServer=${EMAIL_SMTP_SERVER}
      - Email__SmtpPort=${EMAIL_SMTP_PORT}
      - Email__SmtpUser=${EMAIL_SMTP_USER}
      - Email__SmtpPass=${EMAIL_SMTP_PASS}
      - Email__FromAddress=${EMAIL_FROM_ADDRESS}
    networks:
      - vps-network
    expose:
      - "8080"

  urlshorter-frontend:
    image: ghcr.io/jadsonserafim/urlshorter-frontend:latest
    container_name: urlshorter-frontend
    restart: always
    networks:
      - vps-network
    expose:
      - "80"
    volumes:
      - ./images/orangepi.jpg:/usr/share/nginx/html/orangepi.jpg:ro
      - ./images/orangepi2.jpg:/usr/share/nginx/html/orangepi2.jpg:ro

networks:
  vps-network:
    external: true
